# Generated by Django 4.1.2 on 2022-11-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_tag_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='describtion',
            new_name='description',
        ),
    ]
